# Generated by Django 3.1.2 on 2020-10-02 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerOffensiveStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goals_game_winning', models.IntegerField()),
                ('goals_game_tying', models.IntegerField()),
                ('goals_overtime', models.IntegerField()),
                ('goals_shootout', models.IntegerField()),
                ('goals_total', models.IntegerField()),
                ('assists_game_winning', models.IntegerField()),
                ('assists_game_tying', models.IntegerField()),
                ('assists_overtime', models.IntegerField()),
                ('assists_total', models.IntegerField()),
                ('points', models.FloatField()),
                ('shots_total', models.IntegerField()),
                ('shots_on_goal_total', models.IntegerField()),
                ('shots_hit_frame', models.IntegerField()),
                ('shots_penalty_shot_taken', models.IntegerField()),
                ('shots_penalty_shot_scored', models.IntegerField()),
                ('shots_penalty_shot_missed', models.IntegerField()),
                ('shots_penalty_shot_percentage', models.FloatField()),
                ('shots_shootout_taken', models.IntegerField()),
                ('shots_shootout_scored', models.IntegerField()),
                ('shots_shootout_missed', models.IntegerField()),
                ('shots_shootout_percentage', models.FloatField()),
                ('giveaways', models.IntegerField()),
                ('offsides', models.IntegerField()),
                ('corner_kicks', models.IntegerField()),
                ('hat_tricks', models.IntegerField()),
                ('goals_own', models.IntegerField()),
                ('free_kicks', models.IntegerField()),
            ],
        ),
    ]
